=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "HexString": {
            "type": "string",
            "pattern": "^(?:[0-9A-Fa-f]{2}\\s?)+$"
        },
        "PatchHEX": {
            "description": "Base for patches replacing a hex pattern with another.",
            "type": "object",
            "properties": {
                "File": {
                    "type": "string",
                    "description": "The name of the file being patched."
                },
                "Before": {
                    "$ref": "#/definitions/HexString",
                    "description": "The hexadecimal representation of the code before the patch."
                },
                "After": {
                    "$ref": "#/definitions/HexString",
                    "description": "The hexadecimal representation of the code after the patch."
                },
                "Behavior": {
                    "type": "string",
                    "enum": [
                        "First",
                        "Last",
                        "All",
                        "Single"
                    ],
                    "description": "The Behavior when the pattern matches more than once in the input.",
                    "default": "Single"
                }
            },
            "required": [
                "File",
                "Before",
                "After"
            ]
        },
        "PatchFunctionHEX": {
            "description": "Patches a class method by replacing a hex pattern with another.",
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/PatchHEX"
                }
            ],
            "properties": {
                "Type": {
                    "type": "string",
                    "const": "PatchFunctionHEX"
                },
                "Class": {
                    "type": "string",
                    "description": "The name of the class within the file being patched."
                },
                "Function": {
                    "type": "string",
                    "description": "The name of the function or method being patched."
                }
            },
            "required": [
                "Type",
                "Class",
                "Function"
            ]
        },
        "PatchObjectHEX": {
            "description": "Patches a class method by replacing a hex pattern with another.",
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/PatchHEX"
                }
            ],
            "properties": {
                "Type": {
                    "type": "string",
                    "const": "PatchObjectHEX"
                },
                "Object": {
                    "type": "string",
                    "description": "The name of the object within the file being patched."
                }
            },
            "required": [
                "Type",
                "Object"
            ]
        }
    },
    "type": "object",
    "properties": {
        "Description": {
            "type": "string",
            "description": "A brief description of the fix or change."
        },
        "Author": {
            "type": "string",
            "description": "The name of the author who made the fix or change."
        },
        "Builds": {
            "type": "array",
            "description": "An array of build numbers associated with the fix or change.",
            "items": {
                "type": "integer"
            }
        },
        "Patches": {
            "type": "array",
            "description": "An array of patches applied to the game.",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/PatchFunctionHEX"
                    },
                    {
                        "$ref": "#/definitions/PatchObjectHEX"
                    }
                ]
            }
        }
    },
    "required": [
        "Description",
        "Author",
        "Builds",
        "Patches"
    ]
}

=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/Mods/FixCadorSpawnPosition.json
{
    "$schema": "https://raw.githubusercontent.com/BigBoot/GiganticEmu/master/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json",
    "Description": "Fixes Cadors spawn position by taking his height into account",
    "Author": "CrazyMetic",
    "Builds": [
        510547
    ],
    "Patches": [
        {
            "Type": "PatchObjectHEX",
            "File": "DYNPAWN_Adept_SF.upk",
            "Object": "skAdept2_Charge_Skill",
            "Before": "E3 01 00 00 00 00 00 00 3F 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
            "After": "E3 01 00 00 00 00 00 00 3F 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01"
        },
        {
            "Type": "PatchObjectHEX",
            "File": "DYNPAWN_Adept_SF.upk",
            "Object": "skAdept2_Charge_Skill",
            "Before": "1F 06 00 00 00 00 00 00 D1 04 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 A0 40",
            "After": "1F 06 00 00 00 00 00 00 D1 04 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 7A 43"
        }
    ]
}

=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/Mods/EnableDeveloperConsole.json
{
    "$schema": "https://raw.githubusercontent.com/BigBoot/GiganticEmu/master/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json",
    "Description": "Enable the developer console",
    "Author": "BigBoot",
    "Builds": [
        510547
    ],
    "Patches": [
        {
            "Type": "PatchFunctionHEX",
            "File": "RxGame.upk",
            "Class": "RxPlayerController",
            "Function": "IsDeveloper",
            "Before": "04 19 51 19 01 37 F3 FF FF 09 00 9F F4 FF FF",
            "After": "0B 19 51 19 01 37 F3 FF FF 09 00 9F F4 FF FF"
        },
        {
            "Type": "PatchFunctionHEX",
            "File": "RxGame.upk",
            "Class": "RxPlayerController",
            "Function": "IsDeveloper",
            "Before": "04 28 04 3A 96 55 00 00",
            "After": "04 27 04 3A 96 55 00 00"
        }
    ]
}

=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/Mods/AddRutgerSkillCooldown.json
{
    "$schema": "https://raw.githubusercontent.com/BigBoot/GiganticEmu/master/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json",
    "Description": "Adds CD Back to Rutger's Burrow",
    "Author": "CrazyMetic",
    "Builds": [
        510547
    ],
    "Patches": [
        {
            "Type": "PatchObjectHEX",
            "File": "DYNPAWN_Stoneskin_SF.upk",
            "Object": "skStoneskin3_Burrow_Skill_Teleport",
            "Before": "61 06 00 00 00 00 00 00 60 04 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 00",
            "After": "4D 04 00 00 00 00 00 00 60 04 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 A0 41"
        }
    ]
}

=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/Mods/DisableLobbyCountdown.json
{
    "$schema": "https://raw.githubusercontent.com/BigBoot/GiganticEmu/master/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json",
    "Description": "Disable the countdown in the lobby for servers",
    "Author": "BigBoot",
    "Builds": [
        510547
    ],
    "Patches": [
        {
            "Type": "PatchFunctionHEX",
            "File": "RxGame.upk",
            "Class": "RxPreGameGRI",
            "Function": "UpdateCountdowns",
            "Before": "A6 01 80 B5 00 00 16",
            "After": "8D 01 80 B5 00 00 16"
        }
    ]
}

=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/Mods/FixDedicatedServerTeamAssignment.json
{
    "$schema": "https://raw.githubusercontent.com/BigBoot/GiganticEmu/master/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json",
    "Description": "Fix players being forced to team 1 for dedicated servers",
    "Author": "BigBoot",
    "Builds": [
        510547
    ],
    "Patches": [
        {
            "Type": "PatchFunctionHEX",
            "File": "RxGame.upk",
            "Class": "RxGameInfo",
            "Function": "PostLogin",
            "Before": "9A 38 3A 19 01 A4 F3 FF FF 09 00 0A FD FF FF 00 01 0A FD FF FF 38 3A 24 01 16",
            "After": "9A 38 3A 19 01 A4 F3 FF FF 09 00 0A FD FF FF 00 01 0A FD FF FF 38 3A 24 04 16",
            "Behavior": "All"
        }
    ]
}

=== BigBoot/GiganticEmu/GiganticEmu.ModdingToolkit/Resources/Mods/FixDedicatedServerMinionLoading.json
{
    "$schema": "https://raw.githubusercontent.com/BigBoot/GiganticEmu/master/GiganticEmu.ModdingToolkit/Resources/GiganticEmu.Mod.Schema.json",
    "Description": "Fix black screen when joining lobby on for a dedicated server",
    "Author": "BigBoot",
    "Builds": [
        510547
    ],
    "Patches": [
        {
            "Type": "PatchFunctionHEX",
            "File": "RxGame.upk",
            "Class": "RxHeroSelectorPRI",
            "Function": "AreNonPlatformMinionLoadoutsAllowed",
            "Before": "00 0A FD FF FF 00 01 0A FD FF FF 38 3A 24 01 16",
            "After": "00 0A FD FF FF 00 01 0A FD FF FF 38 3A 24 04 16"
        }
    ]
}
